Fixed GPS tracker issue going on sleep
ViSense-Tech/nrf52-sensors pull request #20
Opened 2023-12-19 14:41 UTC by adhilxavier

json root object was creating only once before entering wake time loop. Now creating and refreshing it. Updated buff size because config payload size was more than 255

2023-12-19 14:49 UTC, infolitzofficial requested changes

2023-12-19 14:49 UTC, infolitzofficial commented on nRF_GPSTrackerCode/src/BLE/BleService.c
> +#define VND_MAX_LEN 350
Why is this size increased ?

2023-12-19 14:49 UTC, infolitzofficial commented on nRF_GPSTrackerCode/src/Json/JsonHandler.c
> -    char cbuff[150] = {0};
Make sure you add comments for such changes. what is the reason behind raising this value to 500 ? @adhilxavier

2023-12-19 16:04 UTC, adhilxavier commented on nRF_GPSTrackerCode/src/BLE/BleService.c
> +#define VND_MAX_LEN 350
We tried to configure with all the configurable parameters in GPS tracker and the config payload was beyond 247 bytes. So for the safer side updated the buff size to 300 to 350 bytes.

2023-12-19 16:08 UTC, adhilxavier commented on nRF_GPSTrackerCode/src/Json/JsonHandler.c
> -    char cbuff[150] = {0};
Same reason mentioned in the above comment. But I feel that it is better to use the same size here also 350 instead of 500. I will update the comments and test again here with the reduced buff size 350 and update the results

2023-12-20 04:15 UTC, infolitzofficial commented on nRF_GPSTrackerCode/src/BLE/BleService.c
> +#define VND_MAX_LEN 350
> We tried to configure with all the configurable parameters in GPS tracker and the config payload was beyond 247 bytes. So for the safer side updated the buff size from 300 to 350 bytes.

So are we able to send payload more than 255 in in a single write ? @adhilxavier

2023-12-20 04:16 UTC, infolitzofficial commented on nRF_GPSTrackerCode/src/Json/JsonHandler.c
> -    char cbuff[150] = {0};
@adhilxavier  please add a comment in the code about this condition.

2023-12-26 03:34 UTC, adhilxavier commented on nRF_GPSTrackerCode/src/BLE/BleService.c
> +#define VND_MAX_LEN 350
Yes we are able to send more than 255 bytes in a single write now.

2023-12-26 03:34 UTC, adhilxavier commented on nRF_GPSTrackerCode/src/Json/JsonHandler.c
> -    char cbuff[150] = {0};
ok

2023-12-26 03:37 UTC, adhilxavier commented on nRF_GPSTrackerCode/src/BLE/BleService.c
> +#define VND_MAX_LEN 350
I have done some changes to resolve the reset issue shyni mentioned last week.

2023-12-27 09:27 UTC, speethambaran commented on nRF_GPSTrackerCode/src/BLE/BleService.c
> +#define VND_MAX_LEN 350
Go ahead and merge.

2023-12-27 09:28 UTC, speethambaran approved these changes
Can merge

2023-12-27 09:28 UTC, merged

2023-12-27 09:28 UTC, adhilxavier commented
Closing this PR